name: pastis
channels:
    - default
dependencies:
    - python<=3.11
    - setuptools>=50.0, <60.0
    - pip
    - pip:
        - sphinx
        - numpy
        - scipy
        - scikit-learn
        - matplotlib
        - iced
        - pastis
        - joblib
        - cython
        - pandas
        - sphinx-gallery
        - numpydoc
        - pytest
        - nose
        - autograd
