name: pastis
channels:
    - default
dependencies:
    - python>3
    - numpy>1.16, <=2.0  # for installing iced
    - pandas
    - scikit-learn
    - scipy
    - pip
    - pip:
        - sphinx
        - matplotlib
        - iced
        - joblib
        - sphinx-gallery
        - numpydoc
        - pytest
        - nose
        - autograd
