name: pastis
channels:
    - default
dependencies:
    - python>3
    - conda-forge::cython
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - pip
    - pip:
        - sphinx
        - matplotlib
        - iced
        - joblib
        - sphinx-gallery
        - numpydoc
        - pytest
        - nose
        - autograd
