name: pastis
channels:
    - default
dependencies:
    - python
    - pip
    - pip:
        - sphinx
        - numpy
        - scipy
        - sklearn
        - matplotlib
        - iced
        - pastis
        - joblib
        - pandas
        - sphinx-gallery
        - numpydoc
        - pytest
        - nose
        - autograd
