name: pastis
channels:
    - default
dependencies:
    - python
    - setuptools>=77
    - numpy
    - absl-py
    - pip
    - pip:
        - sphinx
        - scipy
        - scikit-learn
        - matplotlib
        - git+https://github.com/gesinecauer/iced.git@fix_install_from_repo
        - joblib
        - pandas
        - sphinx-gallery
        - numpydoc
        - pytest
        - nose
        - jax
